bookfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'bookfinder'

urlpatterns = [
    path('all', views.test, name='test'),
    #path('all/', views.SearchProduct.as_view(), name='search book'),
    ]

carts/urls.py
from django.urls import path, include
from . import views 

app_name = 'cart'


urlpatterns = [
  	path('', views.cart_home, name='home'),
  	path('update/', views.cart_update, name='update'),
    ]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookfinder/', include('bookfinder.urls', namespace='bookfinder')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='cart')),
    ]


#static file link
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views 


app_name = 'products'


urlpatterns = [
	#class based url
	path('', views.ProductListView.as_view(), name='product_list'),
	path('book/detail/<slug:slug>', views.ProductDetailView.as_view(), name='details'),
	path('books/category/<slug:slug>', views.GetItembyCategory.as_view(), name='item_by_category'),
	path('books/popular', views.PopularBooks.as_view(), name='popular_books'),
	path('books/categories', views.BooksByCategory.as_view(), name='category'),
	path('books/category/writers', views.BooksByWriters.as_view(), name='writers'),
	path('books/category/publishers', views.BooksByPublishers.as_view(), name='publishers'),
	path('toys', views.AllToys.as_view(), name='toys'),
	path('blog', views.Blog.as_view(), name='blog'),
	



	]

templates/base.html
{% load staticfiles %}
{%url 'bookfinder:test' as all_books%}
{%url 'products:product_list' as all_products%}
{%url 'products:popular_books' as popuar_books%}
{%url 'products:category' as book_category%}
{%url 'products:writers' as writers%}
{%url 'products:publishers' as publishers%}
{%url 'products:toys' as toys%}
{%url 'products:blog' as blog%}
{%url 'products:login' as login%}
{%url 'products:logout' as logout%}
{%url 'cart:home' as cart_url%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/animate.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    {% block stylesheet %}
    {% endblock stylesheet %}
    <style>
    </style>
</head>

<body>
    <!-- top section -->
    <div class="head-banner">
        <div class="container">
            <div class="row">
                <div class="banner-text">
                    <span class="text"><i class="fas fa-mobile-alt"></i>২ - ৫ কার্য দিবসের মধ্যে ডেলিভারি। ডেলিভারি চার্জ মাত্র ৪০ টাকা তবে ১০০০ টাকার পণ্য কিনলে ডেলিভারি একদম ফ্রি। </div>
                    <div class="banner-link">
                        <button class="register">register</button><button class="login">login</button>
                        <span class="banner-social-icon">
                            <a href="#"><i class="fab fa-facebook-square"></i></a>
                            <a href="#"><i class="fab fa-twitter-square"></i></a>
                            <a href="#"><i class="fab fa-google-plus-square"></i></a>
                        </span>
                </div>
            </div>
        </div>
    </div>
  
    <!-- search section -->
    <div class="container">
        <div class="row search">
            <div class="col-md-2"><img src="{%static 'image/logo.jpg'%}" alt="logo"></div>
                <div class="col-md-8 search-field">
                    <form action="{%url 'bookfinder:test' %}" method="GET">
                        <input type="text" name="q" value="{{request.GET.q}}" placeholder=" বইয়ের নাম ও লেখক দিয়ে অনুসন্ধান করুন">
                        <input type="submit" class="search-btn" value="অনুসন্ধান">
                    </form>
                </div>
                <div class="col-md-2 mobile-call">
                    <span><p>মোবাইলে অর্ডার দিন</p><p>0176-2052120</p></span>
                    <span class="call-logo"><i class="fas fa-headset"></i></span>
                </div>
            </div>
        </div>
        <!-- navbar -->
        <header>
            <!-- End most top info -->
            <nav class="navbar  navbar-expand-lg navbar-light top-navbar" data-toggle="sticky-onscroll">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">
                        <ul class="navbar-nav top-nav-item">
                            <li class="nav-item {%if request.path == all_products%} active{%endif%}">
                                <a class="nav-link" href="{{all_products}}">হোম </a>
                            </li>
                            <li class="nav-item {%if request.path == all_books%} active{%endif%}">
                                <a class="nav-link" href="{{all_books}}">সকল বই</a>
                            </li>
                            <li class="nav-item {%if request.path == popuar_books%} active{%endif%}">
                                <a class="nav-link" href="{{popuar_books}}">জনপ্রিয় বই</a>
                            </li>
                            <li class="nav-item {%if request.path == book_category%} active{%endif%}">
                                <a class="nav-link" href="{{book_category}}">বিষয় সমূহ</a>
                            </li>
                            <li class="nav-item {%if request.path == writers%} active{%endif%}">
                                <a class="nav-link" href="{{writers}}">লেখক</a>
                            </li>
                            <li class="nav-item {%if request.path == publishers%} active{%endif%}">
                                <a class="nav-link" href="{{
publishers}}">প্রকাশক</a>
                            </li>
                            <li class="nav-item {%if request.path ==  toys%} active{%endif%}">
                                <a class="nav-link" href="{{ toys}}">খেলনা </a>
                            </li>
                            <li class="nav-item {%if request.path == blog%} active{%endif%}"><a href="{{blog}}" class="nav-link">ব্লগ</a></li>
                            <!--
                       {% if request.user.is_authenticated %}
                        <li class="nav-item {%if request.path == login%} active{%endif%}"><a href="{{login}}" class="nav-link">ব্লগ</a></li>
                            {% else %}
                              <li class="nav-item {%if request.path == logout%} active{%endif%}"><a href="{{logout}}" class="nav-link">ব্লগ</a></li>
                                                                                    
                      
                      {% endif %}
                       -->
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- End top header-->
        <div class="banner">
            <div class="container">
                <div class="row">
                    <div class="banner-content">
                        {% block banner-text %}
                        WAFI (وفي) মুলত একটি অ্যারাবিক শব্দ । শব্দটির মানে হল বিশ্বস্ত। আমরা এমন একটি ই-কমার্স প্লাটফর্ম ডেভেলপ করছি যেখান থেকে আপনি গুনগত মান সম্পন্ন প্রোডাক্ট এবং সার্ভিস অপ্রয়োজনীয় বেশী অর্থ খরচ না করেই পেতে পারেন।
                        {% endblock banner-text %}
                    </div>
                </div>
            </div>
        </div>
        <a href="{{cart_url}}">
<div class="cart-bag">
    <p class="circle">o</p>
    <p class="item">{{request.session.cart_items}}</p>
    <p class="price">{{request.session.cart_total}}.00 ৳</p>
</div>
</a>


        {% block content %}
        {% endblock content %}

  
        <!-- footer -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 blog-post">
                        <h2>সাম্প্রতিক পোস্ট</h2>


                        <div class="post_meta">
                            <span class="date-time">
                                        <span>17</span>
                                        <br>
                            <span>Sep</span>
                            </span>
                          <div class="blog-post-detail">
                                <div class="entry-title">
                                <a href="#" rel="bookmark">
                                        পারফিউমেন্সের প্রোডাক্ট-লিস্ট [ মূল্য সহ ] </a>
                            </div>
                            <p class="entry-desc">
                                √√√ রিফ্রেশমেন্টঃ [ মোস্ট পপুলার ক্যাটাগরি ]
                                * পোলো ব্লু [...] </p>
                          </div>
                        </div>
                        <div class="post_meta">
                            <span class="date-time">
                                        <span>17</span>
                                        <br>
                            <span>Sep</span>
                            </span>
                          <div class="blog-post-detail">
                                <div class="entry-title">
                                <a href="#" rel="bookmark">
                                        পারফিউমেন্সের প্রোডাক্ট-লিস্ট [ মূল্য সহ ] </a>
                            </div>
                            <p class="entry-desc">
                                √√√ রিফ্রেশমেন্টঃ [ মোস্ট পপুলার ক্যাটাগরি ]
                                * পোলো ব্লু [...] </p>
                          </div>
                        </div>
                    </div>
                    <div class="col-md-3 important-links">
                        <h2>প্রয়োজনীয় লিংক</h2>
                        <ul>
                            <li><a href="">যোগাযোগ করুন</a></li>
                            <li><a href="">ব্লগ</a></li>
                            <li><a href="">শপিং ব্যাগ</a></li>
                            <li><a href="">আপনার পছন্দের তালিকা</a></li>
                            <li><a href="">প্রশ্নোত্তর</a></li>
                            <li><a href="">কিভাবে কেনাকাটা করবেন ?</a></li>
                            <li><a href="">নীতিমালা</a></li>
                            <li><a href="">শর্তাবলী</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 important-topics">
                        <h2>তথ্যভাণ্ডার</h2>
                        <div class="topic-individual">
                            <a href="">ইসলামী গেম</a>
                            <a href="">হালাল বিনোদন</a>
                            <a href="">beye</a>
                            <a href="">Doll</a>
                            <a href="">jibon</a>
                            <a href="">Leadership Lessons: From the Life of Rasoolullah</a>
                            <a href="">marriage</a>
                            <a href="">tatto</a>
                            <a href="">totto</a>
                            <a href="">অসামান্য গুনাবলী</a>
                            <a href="">আদর্শ</a>
                            <a href="">জাস্টিস মুফতী মুহাম্মদ তকী উসমানী</a>
                            <a href="">জীবন</a>
                            <a href="">তত্ত্ব ছেড়ে জীবনে</a>
                            <a href="">দাম্পত্য</a>
                            <a href="">পারফিউম অয়েল</a>
                            <a href="">বিয়ে</a>
                            <a href="">বিশ্বাস</a>
                            <a href="">রাসুলুল্লাহ (সঃ)</a>
                            <a href="">লক্ষ্য</a>
                            <a href="">সংসার</a>
                            <a href="">সাফল্য</a>
                            <a href="">সিয়ান পাবলিকেশন</a>
                            <a href="">স্বামী-স্ত্রী</a> 
                        </div>
                    </div>
                    <div class="col-md-3 newslatter">
                        <h2>নিউজ লেটার</h2>
                        <p>সর্বশেষ খবর জানতে ইমেইল প্রদান করুন</p>
                        <form action="" class="form-group">
                            <input type="email" placeholder="Enter your email ..." class="form-control">
                            <br>
                            <button class="btn btn-default">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="copyright">কপিরাইট © ২০১৬ Wafilife। ডিজাইন Wafi Solutions</div>
        </div>



        <!-- scripts -->
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" integrity="sha384-kW+oWsYx3YpxvjtZjFXqazFpA7UP/MbiY4jvs+RWZo2+N94PFZ36T6TFkc9O3qoB" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="{%static 'js/owl.carousel.min.js'%}"></script>
        <script src="{%static 'js/main.js'%}"></script>
</body>

</html>

templates/product_books.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
    	<div class="row">
    		{% if request.GET.q %}
    		<div class="col-12">
    			Result for <b>{{request.GET.q}}</b>
    		<hr>
    		</div>

    		  
    		
    		{% endif %}
			



    	</div>
    	<div class="row">
    		<div class="col-md-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt iure mollitia ea hic debitis temporibus nemo perspiciatis animi velit id natus minima accusamus quod, deleniti quos cumque ratione necessitatibus inventore?</div>
    		<div class="col-md-9 flex-all">
    			{% for product in all %}
    			    
    			<div class="card individual-product all-product">
                            <div class="card-img-top">
                                <div class="card-hoverable">
                                    <div class="card-image">
                                        <img class="img-fluid" src="{{product.image.url}}">

                                        </div>
                                        <div class="overlay">
                                            <div class="text">Hello World</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="product-title">
                                        <span class="card-title"><a href="{%url 'products:details' slug=product.slug%}">{{product.title}}</a></span>
                                    </div>
                                    <div class="product_writer"><span></span><a href="#">{{product.writer.name}}</a></div>
                                    <div class="product-price">
                                        <span><del>{{product.previous_price}} <span>৳</span></del></span><span>{{product.price}} <span>৳</span></span>
                                    </div>
                                    <button type="button" class="btn btn-outline-danger">ক্রয় করুন</button>
                                </div>
                            </div>
    			{% endfor %}
    		 </div>
    		</div>
			
			
    	</div>




{% endblock content %}