carts/urls.py
from django.urls import path, include
from . import views 

app_name = 'cart'


urlpatterns = [
  	path('', views.cart_home, name='home'),
  	path('update/', views.cart_update, name='update'),
    ]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookfinder/', include('bookfinder.urls', namespace='bookfinder')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='cart')),
    ]


#static file link
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views 


app_name = 'products'


urlpatterns = [
	#class based url
	path('', views.ProductListView.as_view(), name='product_list'),
	path('book/detail/<slug:slug>', views.ProductDetailView.as_view(), name='details'),
	path('books/category/<slug:slug>', views.GetItembyCategory.as_view(), name='item_by_category'),
	path('books/popular', views.PopularBooks.as_view(), name='popular_books'),
	path('books/categories', views.BooksByCategory.as_view(), name='category'),
	path('books/category/writers', views.BooksByWriters.as_view(), name='writers'),
	path('books/category/publishers', views.BooksByPublishers.as_view(), name='publishers'),
	path('toys', views.AllToys.as_view(), name='toys'),
	path('blog', views.Blog.as_view(), name='blog'),
	



	]

carts/models.py
from django.db import models
from django.conf import settings 
from products.models import product
from django.db.models.signals import pre_save, post_save
from django.db.models.signals import m2m_changed




User =settings.AUTH_USER_MODEL


class CartManager(models.Manager):

	def new_or_get(self, request):
		cart_id = request.session.get("cart_id", None)
		qs = Cart.objects.filter(id=cart_id)
		if qs.count() == 1:
			new_obj = False
			cart_obj = qs.first()
			if request.user.is_authenticated and cart_obj.user is None:
			 cart_obj.user = request.user
			 cart_obj.save()
		else:
			cart_obj = Cart.objects.new(user=request.user)
			new_obj = True
			request.session['cart_id'] = cart_obj.id
		return cart_obj, new_obj



	def new(self, user=None):
		user_obj = None
		if user is not None:
			if user.is_authenticated:
				user_obj = user
		return self.model.objects.create(user=user_obj)




class Cart(models.Model):
	user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	products = models.ManyToManyField(product, blank=True)
	sub_total = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
	total = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	objects = CartManager()

	def __str__(self):
		return str(self.id)



def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
	
	if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
		products = instance.products.all()
		total = 0
		for x in products:
			total += x.price 
			#print(total)
		if instance.sub_total != total:
			instance.sub_total = total
			instance.save()

#pre_save.connect(pre_save_cart_receiver, sender=Cart)
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance,  *args, **kwargs):
	if instance.sub_total > 0:
		instance.total = instance.sub_total
	else:
		instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from . models import Cart 
from products.models import product 

'''
def cart_create(user=None):
	cart_obj = Cart.objects.create(user=None)
	print('New cart creted')
	return cart_obj
'''


def cart_home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)

	#product = cart_obj.products.all()
	#cart_id = request.session.get('cart_id', None)
	'''
	#print(request.session)
	#print(dir(request.session))
	#key = request.session.session_key
	#print(key)
	#we can access this session dictionary in any page like localhost:8000
	#request.session['first_name'] = "shuvo"
	#del request.session['cart_id']
	#cart_id = request.session.get('cart_id', None)

	#if cart_id is None: #and isinstance(cart_id, int):
		#print('create new cart')
		#cart_obj = Cart.objects.create(user=None)
		#request.session['cart_id'] = cart_obj.id
		#print('New cart created')
	qs = Cart.objects.filter(id=cart_id)
	if qs.count() == 1:
		print('cart id exists')
		cart_obj = qs.first()
		if request.user.is_authenticated and cart_obj.user is None:
			cart_obj.user = request.user
			cart_obj.save()
	else:
		#cart_obj=cart_create(request.user)
		cart_obj = Cart.objects.new(user=request.user)
		request.session['cart_id'] = cart_obj.id
	'''


	context = {
		'cart':cart_obj
	}

	return render(request, 'carts/cart_home.html', context)


def cart_update(request):
	print(request.POST)
	product_id = request.POST.get('product_id')
	if product_id is not None:
		try:
			product_obj = product.objects.get(id=product_id)
		except product.DoesNotExist:
			print("show message to usr, product is gone")
			return redirect("cart:home")

		cart_obj, new_obj = Cart.objects.new_or_get(request)
		#print('cart')
		#print(cart_obj.products.all())
		if product_obj in cart_obj.products.all():
		#print('products removes')
			cart_obj.products.remove(product_obj)
		else:
			#print('product added')
			cart_obj.products.add(product_obj)
		request.session['cart_items'] = cart_obj.products.count()
		request.session['cart_total'] = int(cart_obj.total)
	#cart_obj.products.add(product_id)
	#cart_obj.products.remove(obj)
	#return redirect(product_obj.get_absolute_url())

	return redirect("cart:home")

templates/carts/cart_home.html
{% extends "../base.html" %}


    {% block banner-text %}
    <div class="cart-banner">
<h2>শপিং ব্যাগ</h2>
<p> <a href="{% url 'products:product_list'%}">হোম </a> / শপিং ব্যাগ</p>
</div>
{% endblock banner-text %}

{% block content %}
<div class="container">
    
<div class="row">
	{% if cart.products.exists %}
	    
<table class="table table-bordered cart-table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">পণ্য</th>
                <th scope="col">মূল্য</th>
                <th scope="col">পরিমাণ</th>
                <th scope="col">সর্বমোট</th>
                <th scope="col">বাতিল করুন</th>
            </tr>
        </thead>
        <tbody class="cart-body">
            {% for product in cart.products.all %}
                <tr>
                <td><img src="{{product.image.url}}" alt="product image"> <a href="{%url 'products:details' slug=product.slug%}">{{product.title}}</a></td>
                <td>{{product.price}}</td>
                <td>quantity</td>
                <td>{{product.price}} * quantity</td>
                <td>{% include 'carts/update_cart.html' with product=product cart=cart in_cart=True %}
	</td>
            </tr>
            
            {% endfor %}
        </tbody>

    </table>
    <div class="cart-btn">
    	<button class="btn btn-default">আরও বই ক্রয় করুন</button>
        <button class="btn btn-danger">আপডেট করুন</button>

    </div>
<div class="total">
	
        <p>total {{cart.total}}</p>
	<p>subtotal {{cart.sub_total}}</p>

</div>
	    {%else%}
	<p class="lead">আপনার শপিং ব্যাগ এখন খালি

</p>
<button class="btn btn-default">
শপে ফিরে যান</button>





	
	{% endif %}



</div>
</div>
{% endblock content %}

templates/carts/update_cart.html
    <form action="{%url 'cart:update' %}" method="POST" class="form">
{% csrf_token %}
<input type="hidden" name="product_id" value="{{product.id}}"> 


{% if in_cart %}
<button type="submit" class="btn btn-warning btn-small">Remove</button>
    {%else%}


{% if product in cart_obj.products.all %}
In Cart 
	<button class="btn btn-warning">Remove</button>
	{%else%}
	
	<button type='submit' class="btn btn-primary">Add to Cart</button>
	{% endif %}
	{% endif %}

         </form>

	